include:
  - services/bazarr.yml
  - services/lidarr.yml
  - services/plex.yml
  - services/portainer.yml
  - services/prowlarr.yml
  - services/qbittorrent.yml
  - services/radarr.yml
  - services/sonarr.yml
  - services/tautulli.yml
  - services/watchtower.yml


networks: 
  high-seas: 
    driver: bridge