include:
  - services/couchpotato.yml
  - services/mopidy.yml
  - services/plex.yml
  - services/portainer.yml
  - services/qbittorrent.yml
  - services/watchtower.yml

# services:

#   portainer:
#     image: portainer/portainer
#     container_name: portainer
#     hostname: portainer
#     restart: always
#     command: --templates http://templates/templates.json
#     env_file:
#       - .env
#     ports:
#       - 9000:9000
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock
#       - ${APPS_DIR}/portainer/data:/data
#     environment:
#       - TZ=${TZ}

#   watchtower:
#     image: v2tec/watchtower
#     container_name: watchtower
#     hostname: watchtower
#     restart: always
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock
#     command: --schedule "0 0 4 * * *" --cleanup

#   plex:
#     image: plexinc/pms-docker
#     container_name: plex
#     hostname: plex
#     restart: unless-stopped
#     env_file:
#       - .env
#     ports:
#       - 32400:32400/tcp
#       - 3005:3005/tcp
#       - 8324:8324/tcp
#       - 32469:32469/tcp
#       - 1900:1900/udp
#       - 32410:32410/udp
#       - 32412:32412/udp
#       - 32413:32413/udp
#       - 32414:32414/udp
#     environment:
#       - TZ=${TZ}
#       - PLEX_CLAIM=${PLEX_CLAIM}
#       - ADVERTISE_IP=http://${PLEX_PUBLIC_IP}:32400/
#     volumes:
#       - ${APPS_DIR}/plex/database:/config
#       - ${APPS_DIR}/plex/transcode/temp:/transcode
#       - ${MEDIA_DIR}:/data
#       - ${LOGS_DIR}/plex:/config/Library/Application Support/Plex Media Server/Logs

#   couchpotato:
#     image: linuxserver/couchpotato
#     container_name: couchpotato
#     hostname: couchpotato
#     restart: always
#     env_file:
#       - .env
#     environment:
#       - PUID=${PUID}
#       - PGID=${PGID}
#       - TZ=${TZ}
#       - UMASK_SET=022
#     ports:
#       - 5050:5050
#     volumes:
#       - ${APPS_DIR}/couchpotato:/config
#       - ${DOWNLOAD_DIR}:/downloads
#       - ${MEDIA_DIR}/movies:/movies
#       - ${LOGS_DIR}/couchpotato:/config/data/logs

#   qbittorrent:
#     image: linuxserver/qbittorrent
#     container_name: qbittorrent
#     hostname: qbittorrent
#     restart: always
#     env_file:
#       - .env
#     volumes:
#       - ${APPS_DIR}/qbittorrent:/config
#       - ${DOWNLOAD_DIR}/completed:/downloads
#       - ${LOGS_DIR}/qbittorrent:/config/data/qBittorrent/logs
#     ports:
#       - 8090:8090
#       - 6881:6881
#       - 6881:6881/udp
#     environment:
#       - PUID=${PUID}
#       - PGID=${PGID}
#       - TZ=${TZ}
#       - UMASK_SET=022
#       - WEBUI_PORT=8090

#   mopidy:
#     image: wernight/mopidy
#     container_name: mopidy
#     hostname: mopidy
#     env_file:
#       - .env
#     # environment:
#     #   - PULSE_SERVER=$(PULSE_SERVER)
#     #   - PULSE_COOKIE_DATA=${PULSE_COOKIE_DATA}
#     volumes:
#       - ${APPS_DIR}/mopidy/media:/var/lib/mopidy/media:ro
#       - ${APPS_DIR}/mopidy/local:/var/lib/mopidy/local
#     ports:
#       - 6600:6600
#       - 6680:6680
#     # options:
#     #   - spotify/enabled=false
#     #   - gmusic/enabled=false
#     #   - soundcloud/enabled=false
