include:
  - services/bazarr.yml
  - services/lidarr.yml
  - services/portainer.yml
  - services/prowlarr.yml
  - services/qbittorrent.yml
  - services/radarr.yml
  - services/sonarr.yml

networks: 
  high-seas: 
    driver: bridge