services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    networks:
      - high-seas
    env_file:
      - ../.env
    environment:
      - TZ=${TZ}
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HMS_DIR}/apps/portainer/data:/data
