services:
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    hostname: qbittorrent
    restart: always
    env_file:
      - ../.env
    volumes:
      - ${APPS_DIR}/qbittorrent:/config
      - ${DOWNLOAD_DIR}/completed:/downloads
      - ${LOGS_DIR}/qbittorrent:/config/data/qBittorrent/logs
    ports:
      - 8090:8090
      - 6881:6881
      - 6881:6881/udp
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022
      - WEBUI_PORT=8090
