services:
  radarr: 
    image: lscr.io/linuxserver/radarr:latest 
    container_name: radarr 
    hostname: radarr 
    networks: 
      - high-seas 
    env_file:
      - ../.env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports: 
      - 7878:7878
    volumes: 
      - ${HMS_DIR}/apps/radarr:/config 
      - ${HMS_DIR}/data/movies:/mnt/media 
      - ${HMS_DIR}/data/downloads:/mnt/downloads 
    restart: unless-stopped