services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest 
    container_name: sonarr
    hostname: sonarr
    networks:
      - high-seas
    env_file:
      - ../.env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 8989:8989
    volumes:
      - ${HMS_DIR}/apps/sonarr:/config
      - ${HMS_DIR}/data/tv_shows:/data
    restart: unless-stopped