services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    hostname: sonarr
    restart: unless-stopped
    networks:
      - high-seas
    env_file:
      - ../.env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 8989:8989
    volumes:
      - ${HMS_DIR}/apps/sonarr:/config
      - ${HMS_DIR}/data/tv_shows:/data