services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    hostname: watchtower
    networks:
      - high-seas
    command:
      - --cleanup=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped